"""empty message

Revision ID: 0a4ecbe6eba2
Revises: 
Create Date: 2018-06-12 22:41:14.487524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a4ecbe6eba2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('politicians',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registered_id', sa.Integer(), nullable=True),
    sa.Column('civil_name', sa.String(length=80), nullable=True),
    sa.Column('ascii_civil_name', sa.String(length=80), nullable=True),
    sa.Column('parliamentary_name', sa.String(length=80), nullable=True),
    sa.Column('ascii_parliamentary_name', sa.String(length=80), nullable=True),
    sa.Column('birth', sa.String(length=80), nullable=True),
    sa.Column('party_siglum', sa.String(length=80), nullable=True),
    sa.Column('scholarity', sa.String(length=80), nullable=True),
    sa.Column('hometown', sa.String(length=80), nullable=True),
    sa.Column('position', sa.String(length=80), nullable=True),
    sa.Column('photo_url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('politicians')
    # ### end Alembic commands ###
