"""empty message

Revision ID: 100f318424ed
Revises: 
Create Date: 2018-04-14 09:54:54.908029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '100f318424ed'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('politicians',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('scholarity', sa.String(length=255), nullable=True),
    sa.Column('hometown', sa.String(length=100), nullable=True),
    sa.Column('party_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['party_id'], ['political_parties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'canditacies', 'politicians', ['polician_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'canditacies', type_='foreignkey')
    op.drop_table('politicians')
    # ### end Alembic commands ###
