"""empty message

Revision ID: 229b2b6d36c2
Revises: a516f6060bec
Create Date: 2018-05-08 20:55:13.630807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '229b2b6d36c2'
down_revision = 'a516f6060bec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('politicians', sa.Column('photo_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('politicians', 'photo_url')
    # ### end Alembic commands ###
