"""empty message

Revision ID: 7a961c442bf3
Revises: 229b2b6d36c2
Create Date: 2018-06-09 14:53:41.786541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a961c442bf3'
down_revision = '229b2b6d36c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('politicians', sa.Column('ascii_civil_name', sa.String(length=80), nullable=True))
    op.add_column('politicians', sa.Column('ascii_parliamentary_name', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('politicians', 'ascii_parliamentary_name')
    op.drop_column('politicians', 'ascii_civil_name')
    # ### end Alembic commands ###
